CREATE TABLE Archives (
  Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Title TEXT NOT NULL,
  Url TEXT NOT NULL,
  TextLength BIGINT NOT NULL,
  ImageCount BIGINT NOT NULL,
  PublishTime TEXT NULL,
  Publisher TEXT NULL,
  Content TEXT NOT NULL,
  Category TEXT NOT NULL
);